app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Login
Route::get('/', ['as' => 'login_page', 'uses' => 'HomeController@login_page']);
Route::post('/login',['as' => 'user_login', 'uses' => 'HomeController@user_login']);

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){
	# Logout
	Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
#dashboard_home
	# Dashboard
	Route::get('/', ['as' => 'dashboard', 'uses' => 'HomeController@dashboard_home']);
	Route::get('/annual-sales-json', ['as' => 'annual_sales_json', 'uses' => 'HomeController@annual_sales_json']);
	Route::get('/montly-sales-per-menu-json/{menuid}', ['as' => 'monthly_sales_per_menu_json', 'uses' => 'HomeController@monthly_sales_per_menu_json']);

	# Sales
	Route::group(['prefix' => 'sales'], function(){
		# Cash Register
		Route::get('/', ['as' => 'sales', 'uses' => 'CashRegisterController@sales']);
		# Official Receipt
		Route::get('/or/{id?}', ['as' => 'officialReceiptPrint', 'uses' => 'CashRegisterController@officialReceiptPrint']);
		# Session
		Route::group(['prefix' => 'cart'], function(){
			Route::get('/tables', ['as' => 'tables', 'uses' => 'CashRegisterController@tables']);
			Route::get('/add-customer', ['as' => 'addCustomer', 'uses' => 'CashRegisterController@addCustomer']);
			Route::get('/discount', ['as' => 'addDiscount', 'uses' => 'CashRegisterController@discount']);
			Route::get('/customer-transaction', ['as' => 'customerTransaction', 'uses' => 'CashRegisterController@customerTransaction']);

			Route::get('/datetime', ['as' => 'datetime', 'uses' => 'CashRegisterController@datetime']);

			Route::get('/billout', ['as' => 'billout', 'uses' => 'CashRegisterController@billout']);
			Route::get('/verify/{id?}', ['as' => 'verify', 'uses' => 'CashRegisterController@verify']);
			Route::get('/add', ['as' => 'menuSaleAdd', 'uses' => 'CashRegisterController@menuSaleAdd']);

			Route::get('/list', ['as' => 'menuSaleList', 'uses' => 'CashRegisterController@menuSaleList']);

			Route::get('/cancel', ['as' => 'menuSaleCancel', 'uses' => 'CashRegisterController@cancel']);
			Route::get('/remove-item', ['as' => 'removeItem', 'uses' => 'CashRegisterController@removeItem']);
			Route::get('/delete', ['as' => 'menuSaleDelete', 'uses' => 'CashRegisterController@menuSaleDelete']);

			Route::get('/auth-admin', ['as' => 'authAdmin', 'uses' => 'CashRegisterController@authenticateAdmin']);
		});
	});

	#inventory
	Route::group(['prefix' => 'inventorylist'], function(){
		Route::get('/', ['as' => 'inventorylist', 'uses' => 'InventoryController@index']);
	});

	#settings
	Route::group(['prefix' => 'settings'], function(){
		Route::get('/', ['as' => 'settings', 'uses' => 'SettingsController@index']);
		Route::post('/update', ['as' => 'update_company', 'uses' => 'SettingsController@update_company']);

		Route::get('/terminals', ['as' => 'terminals', 'uses' => 'SettingsController@terminals']);
		Route::get('/edit-terminal/{terminalid}', ['as' => 'edit_terminal', 'uses' => 'SettingsController@edit_terminal']);

		Route::get('/sizes/', ['as' => 'sizes', 'uses' => 'SettingsController@sizes']);
		Route::post('/add-size/', ['as' => 'add_size', 'uses' => 'SettingsController@add_size']);
		Route::get('/remove-size/{id}', ['as' => 'remove_size', 'uses' => 'SettingsController@remove_size']);

		Route::get('/pricing/{id}', ['as' => 'pricing', 'uses' => 'SettingsController@pricing']);
		Route::post('/add-price/', ['as' => 'add_price', 'uses' => 'SettingsController@add_price']);
		Route::get('/remove-price/{id}', ['as' => 'remove_price', 'uses' => 'SettingsController@remove_price']);

		Route::get('/orders/', ['as' => 'orders', 'uses' => 'SettingsController@orders']);
		Route::get('/order-details/{id}', 'SettingsController@check_order_details')->name('admin_check_order_details');
		Route::get('/receive-order/{id}', 'SettingsController@receive_order')->name('admin_receive_order');
		
		Route::get('order-location/{id}', 'SettingsController@user_order_location')->name('order_location');
		#orders


	});
	#tables
	Route::group(['prefix' => 'table-settings'], function(){
		Route::get('/', ['as' => 'table-settings', 'uses' => 'TableController@index']);
		Route::get('/add-table', ['as' => 'add_table_page', 'uses' => 'TableController@add_table_page']);
		Route::post('/add-table-submit', ['as' => 'add_table', 'uses' => 'TableController@add_table']);
		Route::get('/edit-table/{tableid}', ['as' => 'edit_table', 'uses' => 'TableController@edit_table']);
		Route::post('/update-table/', ['as' => 'update_table', 'uses' => 'TableController@update_table']);
		Route::get('/delete-table', ['as' => 'delete_table', 'uses' => 'TableController@delete_table']);
	});

	#sizes
	Route::group(['prefix' => 'sizes'], function(){
		Route::get('/', ['as' => 'sizes', 'uses' => 'MenuController@sizes']);
		Route::post('/add-size', ['as' => 'add_size', 'uses' => 'MenuController@add_size']);
		Route::get('/remove-size/{id}', ['as' => 'remove_size', 'uses' => 'MenuController@remove_size']);
		
	});


	#Inventory
	Route::group(['prefix' => 'inventory'], function(){
		Route::get('/', ['as' => 'inventory', 'uses' => 'InventoryController@index']);
		Route::get('/history/{itemid}', ['as' => 'inventory_history', 'uses' => 'InventoryController@history']);
	});

	#Transaction
	Route::group(['prefix' => 'transaction'], function(){
		Route::get('/', ['as' => 'transaction', 'uses' => 'TransactionController@index']);
	});

	#Items
	Route::group(['prefix' => 'items'], function(){
		Route::get('/', ['as' => 'items', 'uses' => 'ItemController@index']);
		Route::get('/add', ['as' => 'add_item_page', 'uses' => 'ItemController@add_item_page']);
		Route::post('/add_item', ['as' => 'add_item', 'uses' => 'ItemController@add_item']);
		Route::get('/edit_item/{itemid}', ['as' => 'edit_item', 'uses' => 'ItemController@edit_item']);

		Route::get('/inventory/{itemid}', ['as' => 'inventory', 'uses' => 'ItemController@inventory']);

		Route::post('/update_item', ['as' => 'update_item', 'uses' => 'ItemController@update_item']);
		
		Route::get('/delete_item', ['as' => 'delete_item', 'uses' => 'ItemController@delete_item']);
		Route::get('/items_json', ['as' => 'items_json', 'uses' => 'ItemController@items_json']);

		Route::get('/adjustment/{itemid}', ['as' => 'adjustment', 'uses' => 'ItemController@adjustment']);
	});

	#Spoilages
	Route::group(['prefix' => 'spoilages'], function(){
		Route::get('/', ['as' => 'spoilages', 'uses' => 'SpoilagesController@index']);
		Route::get('/add-spoilages', ['as' => 'add_spoilages_page', 'uses' => 'SpoilagesController@add_spoilages_page']);
		Route::post('/add-spoilage', ['as' => 'add_spoilage', 'uses' => 'SpoilagesController@add_spoilage']);
	});

	#purchase
	Route::group(['prefix' => 'purchases'], function(){
		Route::get('/', ['as' => 'purchases', 'uses' => 'PurchasesController@index']);	
		Route::get('/add-purchase', ['as' => 'add_purchase_page', 'uses' => 'PurchasesController@add_purchase_page']);	
		Route::post('/add-item-purchased', ['as' => 'add_item_purchased', 'uses' => 'PurchasesController@add_item_purchased']);	
		Route::post('/add-purchased-order', ['as' => 'add_purchased_order', 'uses' => 'PurchasesController@add_purchased_order']);

		Route::get('/view-purchase-details/{purchaseid}', ['as' => 'view_purchase_details', 'uses' => 'PurchasesController@view_purchase_details']);	

		Route::post('/submit-purchase', ['as' => 'add_purchase', 'uses' => 'PurchasesController@add_purchase']);	
		
	});

	#Category
	Route::group(['prefix' => 'category'], function(){
		Route::get('/', ['as' => 'category', 'uses' => 'CategoryController@index']);
		Route::get('/add_category_page', ['as' => 'add_category_page', 'uses' => 'CategoryController@add_category_page']);
		Route::get('/edit-category/{categoryid}', ['as' => 'edit_category', 'uses' => 'CategoryController@edit_category']);

		Route::post('/add_category', ['as' => 'add_category', 'uses' => 'CategoryController@add_category']);
		Route::get('/delete_category', ['as' => 'delete_category', 'uses' => 'CategoryController@delete_category']);
		Route::post('/update_category', ['as' => 'update_category', 'uses' => 'CategoryController@update_category']);
	});

	#Menu
	Route::group(['prefix' => 'menu'], function(){
		Route::get('/', ['as' => 'menu', 'uses' => 'MenuController@index']);		
		Route::get('/add-menu-page', ['as' => 'add_menu_page', 'uses' => 'MenuController@add_menu_page']);
		Route::post('/add_menu', ['as' => 'add_menu', 'uses' => 'MenuController@add_menu']);
		Route::get('/edit_menu/{menuid}', ['as' => 'edit_menu', 'uses' => 'MenuController@edit_menu']);
		Route::post('/update_menu/', ['as' => 'update_menu', 'uses' => 'MenuController@update_menu']);
		Route::get('/delete_menu/', ['as' => 'delete_menu', 'uses' => 'MenuController@delete_menu']);
		Route::get('/data-json', ['as' => 'menuDataJson', 'uses' => 'MenuController@menuDataJson']);

	#Recipes
		Route::get('/manage_recipes/{menuid}/', ['as' => 'manage_recipes', 'uses' => 'MenuController@manage_recipes']);
		Route::post('/add_recipe', ['as' => 'add_recipe', 'uses' => 'MenuController@add_recipe']);
		Route::get('/delete_recipe/{recipeid}/{menuid}', ['as' => 'delete_recipe', 'uses' => 'MenuController@delete_recipe']);
		# Menu json
	#Prices
		Route::get('/manage-prices/{menuid}/', ['as' => 'manage_prices', 'uses' => 'MenuController@manage_prices']);
		Route::post('/add-price', ['as' => 'add_price', 'uses' => 'MenuController@add_price']);

	});

	

	#Users
	Route::group(['prefix' => 'users', 'middleware' => 'auth'], function(){
		Route::get('/', ['as' => 'users', 'uses' => 'HomeController@users_list']);	

app/Items.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\TransactionItem;
use App\PurchasedItems;
use App\Spoilages;

class Items extends Model
{
    use SoftDeletes;
    
    public $table = 'items';
    public $fillable = ['name', 'unit', 'created_at', 'updated_at'];
    public $timestamps = true;

    protected $dates = ['deleted_at'];

    public function MenuItem()
    {
    	return $this->hasMany('App\MenuItem');
    }
    
    public function cash_register_items()
    {
    	return $this->hasMany('App\CashRegisterItems', 'item_id');
    }

    public function Recipes()
    {
    	return $this->hasMany('App\Recipes', 'item_id');
    }

    public function PurchasedItems() {
    	return $this->belongsTo('App\PurchasedItems', 'item_id');
    }


    public function getCurrentQuantityAttribute()
    {
        $id = $this->id;
        $balance = PurchasedItems::whereItemId($id)->sum('quantity');
        $deductspoilages = Spoilages::whereItemId($id)->sum('quantity');  
        $deduct = TransactionItem::whereItemId($id)->sum('servings');
        $total = ($balance - $deductspoilages) - $deduct;

        return $total;
    }

    public function getLastPurchasedDateAttribute()
    {
        $id = $this->id;
        $date = PurchasedItems::with('Purchases')->whereItemId($id)->orderBy('id' ,'desc')->first();
        return date_format($date->Purchases->purchase_date,'Y-m-d');
    }

    public function getTotalSpoilagesAttribute()
    {
        $id = $this->id;
        $spoilages = Spoilages::whereItemId($id)->sum('quantity');  
        return $spoilages;
    }

     public function getTotalTransactionItemsAttribute()
    {
        $id = $this->id;
        $transactionitems = TransactionItem::whereItemId($id)->sum('servings');
        return $transactionitems;
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use DB;
use App\Items;
use App\PurchasedItems;
use App\TransactionItem;
use App\Spoilages;

use Response;

class ItemController extends Controller
{
    public function index(Request $request)
    {
        
        $search = '';
        if($request->has('search'))
        {
            $search = $request->search;
            $items = Items::where('name', 'LIKE', "%$search%")->paginate(10);
        }
        else
        {
            $items = Items::paginate(10);
        }
        $data = compact('items', 'search');

        return view('items.index', $data);
    }

    public function add_item(Request $request) 
    {
        //dd($request->unit);
    	 $this->validate($request, [
            'name' => 'required|max:255|unique:items,name,NULL,id,deleted_at,NULL',
            'unit' => 'required|max:255|'
        ]);

        $x = Items::create($request->only('name', 'unit'));

        $data = [
            'message' => 'Item has been added.',
            'id' => $x->id,
            'name' => $request->name,
            'unit' => $request->unit
        ];

        return redirect()->route('items')->with('message', 'Success');
    }

    public function add_item_page() 
    {
        return view('items.add-item');
    }

    

    public function delete_item(Request $request)
    {
        $item = Items::find($request->item_id);
        $item->delete();
    }

    public function edit_item(Request $request)
    {
        $items = Items::where('id','=', $request->itemid)->first();
        $data = compact('items');

        return view('items.edit-item', $data);   
    }

    public function update_item(Request $request)
    {
        if($request->name_hidden != $request->name)        {
            $name = 'required|max:255|unique:items,name,NULL,id,deleted_at,NULL';
        }else{
            $name = 'required|max:255';
        }
         $this->validate($request, [
            'name' => $name,
            'unit' => 'required|max:255'
        ]);
        $x = Items::whereId($request->id)->update($request->only('name', 'unit'));
       
        $data = [
            'message' => 'Item has been updated.',
            'id' => $request->id,
            'name' => $request->name,
            'unit' => $request->unit
        ];
        return redirect()->route('edit_item', $request->id)->with('message', 'Success');
    }

    public function items_json(Request $request)
    {
        $search = ($request->has('search')) ? trim($request->search) : '';
        $menu = Items::select('name', DB::raw('CONCAT(id,"~~",unit) AS idunit'))->where('name', 'LIKE', '%' . $search . '%')->lists('name', 'idunit');

        return response()->json($menu);
    }

    public function inventory(Request $request, $id)
    {
        $paginate = 12;
        $page = ($request->has('page'))? trim($request->page) : 1;
        
        $item = Items::whereId($id)->first();
        $purchase = PurchasedItems::select([ 
                                            DB::raw("'Purchase ' AS method"),
                                            DB::raw('purchase_date AS transaction_on'), 
                                            DB::raw("'' AS name"), 
                                            'quantity' 
                                        ])
                    ->leftJoin('purchases', 'purchases.id', '=', 'purchased_items.purchase_id')
                    ->where('purchased_items.item_id', $id);

        $spoilages = Spoilages::select([ 
                                        DB::raw("'Spoilage' AS method"),
                                        DB::raw('spoilage_date AS transaction_on'), 
                                        'users.name', 
                                        DB::raw('(-1 * spoilages.quantity) AS quantity') 
                                       ])
                    ->leftJoin('users', 'users.id', '=', 'spoilages.user_id')
                    ->where('spoilages.item_id', $id);

        $used = TransactionItem::select([ DB::raw("'Transaction' AS method"),'transaction.transaction_on', 'users.name',  DB::raw('(-1 * servings) AS quantity') ])
                ->leftJoin('transaction_menu', 'transaction_menu.id', '=', 'transaction_item.transaction_menu_id')
                ->leftJoin('transaction', 'transaction.id', '=', 'transaction_menu.transaction_id')
                ->leftJoin('users', 'users.id', '=', 'transaction.user_id')
                ->where('transaction_item.item_id', $id)
                ->unionall($purchase)
                ->unionall($spoilages)
                ->orderBy('transaction_on', 'DESC')
                ->get();
        #dd($used);     
        $slice = array_slice($used->toArray(), $paginate * ($page - 1), $paginate, true);
        $stocks = new \Illuminate\Pagination\LengthAwarePaginator($slice, count($used), $paginate, $page);
        #dd($id);
        $path = $id.'/';
        $stocks->setPath($path);
        #dd($stocks);
        $data = compact('item', 'stocks');

        return view('items.inventory', $data);
    }

    public function adjustment(Request $request)
    {

        return view('items.adjustment');
    }
}

resources/views/items/add-item.blade.php
@extends('layouts.app')

@section('content')
@parent

<div class="row">
	<div class="medium-2 columns"></div>
	<div class="medium-10 columns">
		<h3>Add Ingredient</h3>
		<br />
		<div class="row">
			<div class="medium-3 columns"></div>
			<div class="medium-9 columns">
				@if (count($errors) > 0)
				<div class="row">
					<div class="medium-8 columns warning callout" data-closable>
						<ul>
					        @foreach ($errors->all() as $error)
					            <li>{{ $error }}</li>
					        @endforeach
					    </ul>
						<button class="close-button" aria-label="Dismiss alert" type="button" data-close>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				</div>
				@endif
				@if(Session::has('message'))
				<div class="row">
					<div class="medium-8 columns success callout" data-closable>
						Ingredient has been successfully updated!
						<button class="close-button" aria-label="Dismiss alert" type="button" data-close>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				
				</div>
				 @endif
				<form id="add_item" action="{{ route('add_item') }}" method="POST">
					<div class="row">
						<div class="medium-8 columns">
							<label>Item Name
								<input name="name" type="text" placeholder="Item Name" autocomplete="off" value="{{ old('name') }}">
							</label>
						</div>
					</div>
					<div class="row">
						<div class="medium-8 columns">
							<label>Unit of Measure
								<input name="unit" type="text" placeholder="Unit of Measure" autocomplete="off" value="{{ old('unit') }}">
							</label>
						</div>
					</div>
					<div class="row">
						<div class="medium-8 columns">
							<input type="submit" class="button" value="Add">
							<a class="button secondary" href="{{ route('items') }}">Cancel</a>
						</div>
					</div>
					{!! csrf_field() !!}
				</form>
			</div>
		</div>
	</div>
</div>

@stop

resources/views/items/adjustment.blade.php
@extends('layouts.app')

@section('content')
@parent
	<style></style>
	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--1-col"></div>
		<div class="mdl-cell mdl-cell--10-col">
			<h3>Adjustments</h3>
			<div class="mdl-grid">
				<div class="mdl-select mdl-js-select mdl-select--floating-label">
					<select class="mdl-select__input" id="method" name="method">
						<option value=""></option>
						<option value="0">Add</option>
						<option value="1">Deduct</option>
					</select>
					<label id="select_label" class="mdl-select__label" for="method">Method</label>
				</div>	
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ">
					<input class="mdl-textfield__input" name="name" type="text" id="name" value="" />
					<label class="mdl-textfield__label" for="name">Quantity</label>
				</div>	
				
			</div>
		</div>
		<div class="mdl-cell mdl-cell--1-col"></div>
	</div>
	<script type="text/javascript">
		$("#method").change(function(){
			if($('#method').val() != "")
			{
				$('#select_label').hide();
			}else{
				$('#select_label').show();
			}
		});
	</script>
@stop

resources/views/items/edit-item.blade.php
@extends('layouts.app')

@section('content')
@parent
<div class="row">
	<div class="medium-2 columns"></div>
	<div class="medium-10 columns">
		<h3>Edit Ingredient</h3>
		<br />
		<div class="row">
			<div class="medium-3 columns"></div>
			<div class="medium-9 columns">
				@if (count($errors) > 0)
				<div class="row">
					<div class="medium-8 columns success callout" data-closable>
						<ul>
					        @foreach ($errors->all() as $error)
					            <li>{{ $error }}</li>
					        @endforeach
					    </ul>
						<button class="close-button" aria-label="Dismiss alert" type="button" data-close>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				</div>
				@endif
				@if(Session::has('message'))
				<div class="row">
					<div class="medium-8 columns success callout" data-closable>
						Item has been updated!
						<button class="close-button" aria-label="Dismiss alert" type="button" data-close>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				
				</div>
				 @endif
				<form id="edit_item" action="{{ route('update_item') }}" method="POST">
					<div class="row">
						<div class="medium-8 columns">
							<label>Item Name
								<input name="name" type="text" id="name" value="{{ $items->name }}" placeholder="Item Name" autocomplete="off">
								<input name="name_hidden" type="hidden" id="name_hidden" value="{{ $items->name }}" />
							</label>
						</div>
					</div>
					<div class="row">
						<div class="medium-8 columns">
							<label>Unit of Measure
								<input name="unit" type="text" id="unit" value="{{ $items->unit }}" placeholder="Unit of Measure" autocomplete="off">
								<input name="id" type="hidden" id="id" value="{{ $items->id }}"/>
							</label>
						</div>
					</div>
					<div class="row">
						<div class="medium-8 columns">
							<input type="submit" class="button" value="Update">
							<a class="button secondary" href="{{ route('items') }}">Cancel</a>
						</div>
					</div>
					{!! csrf_field() !!}
				</form>
			</div>
		</div>
	</div>
</div>
@stop

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
@parent

<div class="row">
	<div class="medium-2 columns"></div>
	<div class="medium-10 columns">
		<h3><i class="fa fa-cube" aria-hidden="true"></i> &nbsp; Items</h3>
		<br />
		<div class="row">
	  		<div class="large-4 columns">
	  			<a href="{{ route('add_item_page') }}" class="button small">
	  			<i class="fa fa-plus" aria-hidden="true"></i> &nbsp;Add Ingredient</a>
	  		</div>
			<div class="large-4 large-offset-4 columns">
				<form action="" method="get">
					<input type="text" id="search" name="search" placeholder="Search Ingredient" value="{{ $search }}" />
				</form>
			</div>
		</div>
		<table align="center" id="item_table" width="100%">
			<thead>
			<tr>
				<th width="10%"></th>
				<th width="50%">Item Name</th>
				<th width="30%">Unit of Measure</th>
				<th width="10%">Quantity</th>
			</tr>
			</thead>
			<tbody>
			@forelse ($items as $item)
			<tr id="item-row-{{ $item->id }}">
				<td class="text-center">
					<a onclick="DeleteItem({{ $item->id }})" id="delete_item{{ $item->id }}" title="Delete Ingredient">
						<i class="fa fa-trash-o" aria-hidden="true"></i>
					</a> &nbsp;	
					<a href="{{ route('edit_item', $item->id ) }}" id="edit_item{{ $item->id }}" title="Edit Ingredient">
						<i class="fa fa-pencil" aria-hidden="true"></i>
					</a>&nbsp;	
					<a href="{{ route('inventory', $item->id) }}" title="Ingredient Inventory History">
						<i class="fa fa-history" aria-hidden="true"></i>
					</a>
				</td>
				<td>
					<span class="item-name-current">{{ $item->name }}</span>
				</td>
				<td>
					<span class="item-unit-current">{{ $item->unit }}</span>
				</td>
				<td>{{ $item->current_quantity }}</td>
			</tr> 
			@empty
				<tr id="no-ingredient"><td colspan="4" style="text-align:center;">No Ingredients Yet</td></tr>

			@endforelse
			</tbody>
		</table>
		<div align="center">
			@if(!$items->isEmpty())
			{{ $items->render() }}
			@endif
		</div>
	</div>
</div>
<script type="text/javascript">
	function DeleteItem(itemid, selector)
	{
		if(confirm("Are you sure to delete this?") ==  true){
			$.ajax({
				type : 'GET',
				url : '{{ route("delete_item") }}',
				data : 'item_id='+itemid,
				cache : false,
				dataType : "script"
			}).done(function(response) {
				$(selector).closest("tr").remove();
				$('#item-row-'+itemid).remove();
			}).fail(function(jqXHR, textStatus, y) {	
				//alert(textStatus);
			});
		}
	}
</script>

@stop

resources/views/items/inventory.blade.php
@extends('layouts.app')

@section('content')
@parent
	<div class="row">
		<div class="medium-2 columns"></div>
		<div class="medium-10 columns"><br />
			<div class="row">
				<div class="medium-1 columns">
					<a class="button secondary" href="{{ route('items') }}" title="Back">
						<i class="fa fa-arrow-left" aria-hidden="true"></i>
					</a>
				</div>
				<div class="medium-10 columns">
					<h4>Ingredient <U>{{ strtoupper($item->name) }}</U> History</h4>
					<table width="100%">
						<thead>
							<tr>
								<th width="20%">Quantity</th>
								<th width="20%">Method</th>
								<th width="30%">Date Tracked</th>
								<th width="30%">User</th>
							</tr>
						</thead>
						<tbody>
							@forelse($stocks as $row)
							@if($row['name'] == '')
							<tr style="color:green">
							@else
							<tr style="color:red">
							@endif
								<td>{{ $row['quantity'] }}</td>
								<td>{{ $row['method'] }}</td>
								<td>{{ $row['transaction_on'] }}</td>
								<td>{{ $row['name'] }}</td>
							</tr>
							@empty
								<tr><td colspan="4" style="text-align:center;">No History Yet</td></tr>
							@endforelse
						</tbody>
					</table>
					<div align="center">
						@if(!$stocks->isEmpty())
							{!! str_replace('/?', '?', $stocks->render()) !!}
						@endif
					</div>	
				</div>
		<!-- <div class="mdl-cell mdl-cell--1-col">
			<button class="mdl-button mdl-button--fab mdl-button--primary" title="Add Inventory" style="right:0;bottom:0; position:absolute; margin:25px; "> 
				<i class="material-icons">add</i>
			</button>
		</div> -->
			</div>
		</div>
	</div>
			

@stop