app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Login
Route::get('/', ['as' => 'login_page', 'uses' => 'HomeController@login_page']);
Route::post('/login',['as' => 'user_login', 'uses' => 'HomeController@user_login']);

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){
	# Logout
	Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
#dashboard_home
	# Dashboard
	Route::get('/', ['as' => 'dashboard', 'uses' => 'HomeController@dashboard_home']);
	Route::get('/annual-sales-json', ['as' => 'annual_sales_json', 'uses' => 'HomeController@annual_sales_json']);
	Route::get('/montly-sales-per-menu-json/{menuid}', ['as' => 'monthly_sales_per_menu_json', 'uses' => 'HomeController@monthly_sales_per_menu_json']);

	# Sales
	Route::group(['prefix' => 'sales'], function(){
		# Cash Register
		Route::get('/', ['as' => 'sales', 'uses' => 'CashRegisterController@sales']);
		# Official Receipt
		Route::get('/or/{id?}', ['as' => 'officialReceiptPrint', 'uses' => 'CashRegisterController@officialReceiptPrint']);
		# Session
		Route::group(['prefix' => 'cart'], function(){
			Route::get('/tables', ['as' => 'tables', 'uses' => 'CashRegisterController@tables']);
			Route::get('/add-customer', ['as' => 'addCustomer', 'uses' => 'CashRegisterController@addCustomer']);
			Route::get('/discount', ['as' => 'addDiscount', 'uses' => 'CashRegisterController@discount']);
			Route::get('/customer-transaction', ['as' => 'customerTransaction', 'uses' => 'CashRegisterController@customerTransaction']);

			Route::get('/datetime', ['as' => 'datetime', 'uses' => 'CashRegisterController@datetime']);

			Route::get('/billout', ['as' => 'billout', 'uses' => 'CashRegisterController@billout']);
			Route::get('/verify/{id?}', ['as' => 'verify', 'uses' => 'CashRegisterController@verify']);
			Route::get('/add', ['as' => 'menuSaleAdd', 'uses' => 'CashRegisterController@menuSaleAdd']);

			Route::get('/list', ['as' => 'menuSaleList', 'uses' => 'CashRegisterController@menuSaleList']);

			Route::get('/cancel', ['as' => 'menuSaleCancel', 'uses' => 'CashRegisterController@cancel']);
			Route::get('/remove-item', ['as' => 'removeItem', 'uses' => 'CashRegisterController@removeItem']);
			Route::get('/delete', ['as' => 'menuSaleDelete', 'uses' => 'CashRegisterController@menuSaleDelete']);

			Route::get('/auth-admin', ['as' => 'authAdmin', 'uses' => 'CashRegisterController@authenticateAdmin']);
		});
	});

	#inventory
	Route::group(['prefix' => 'inventorylist'], function(){
		Route::get('/', ['as' => 'inventorylist', 'uses' => 'InventoryController@index']);
	});

	#settings
	Route::group(['prefix' => 'settings'], function(){
		Route::get('/', ['as' => 'settings', 'uses' => 'SettingsController@index']);
		Route::post('/update', ['as' => 'update_company', 'uses' => 'SettingsController@update_company']);

		Route::get('/terminals', ['as' => 'terminals', 'uses' => 'SettingsController@terminals']);
		Route::get('/edit-terminal/{terminalid}', ['as' => 'edit_terminal', 'uses' => 'SettingsController@edit_terminal']);

		Route::get('/sizes/', ['as' => 'sizes', 'uses' => 'SettingsController@sizes']);
		Route::post('/add-size/', ['as' => 'add_size', 'uses' => 'SettingsController@add_size']);
		Route::get('/remove-size/{id}', ['as' => 'remove_size', 'uses' => 'SettingsController@remove_size']);

		Route::get('/pricing/{id}', ['as' => 'pricing', 'uses' => 'SettingsController@pricing']);
		Route::post('/add-price/', ['as' => 'add_price', 'uses' => 'SettingsController@add_price']);
		Route::get('/remove-price/{id}', ['as' => 'remove_price', 'uses' => 'SettingsController@remove_price']);

		Route::get('/orders/', ['as' => 'orders', 'uses' => 'SettingsController@orders']);
		Route::get('/order-details/{id}', 'SettingsController@check_order_details')->name('admin_check_order_details');
		Route::get('/receive-order/{id}', 'SettingsController@receive_order')->name('admin_receive_order');
		
		Route::get('order-location/{id}', 'SettingsController@user_order_location')->name('order_location');
		#orders


	});
	#tables
	Route::group(['prefix' => 'table-settings'], function(){
		Route::get('/', ['as' => 'table-settings', 'uses' => 'TableController@index']);
		Route::get('/add-table', ['as' => 'add_table_page', 'uses' => 'TableController@add_table_page']);
		Route::post('/add-table-submit', ['as' => 'add_table', 'uses' => 'TableController@add_table']);
		Route::get('/edit-table/{tableid}', ['as' => 'edit_table', 'uses' => 'TableController@edit_table']);
		Route::post('/update-table/', ['as' => 'update_table', 'uses' => 'TableController@update_table']);
		Route::get('/delete-table', ['as' => 'delete_table', 'uses' => 'TableController@delete_table']);
	});

	#sizes
	Route::group(['prefix' => 'sizes'], function(){
		Route::get('/', ['as' => 'sizes', 'uses' => 'MenuController@sizes']);
		Route::post('/add-size', ['as' => 'add_size', 'uses' => 'MenuController@add_size']);
		Route::get('/remove-size/{id}', ['as' => 'remove_size', 'uses' => 'MenuController@remove_size']);
		
	});


	#Inventory
	Route::group(['prefix' => 'inventory'], function(){
		Route::get('/', ['as' => 'inventory', 'uses' => 'InventoryController@index']);
		Route::get('/history/{itemid}', ['as' => 'inventory_history', 'uses' => 'InventoryController@history']);
	});

	#Transaction
	Route::group(['prefix' => 'transaction'], function(){
		Route::get('/', ['as' => 'transaction', 'uses' => 'TransactionController@index']);
	});

	#Items
	Route::group(['prefix' => 'items'], function(){
		Route::get('/', ['as' => 'items', 'uses' => 'ItemController@index']);
		Route::get('/add', ['as' => 'add_item_page', 'uses' => 'ItemController@add_item_page']);
		Route::post('/add_item', ['as' => 'add_item', 'uses' => 'ItemController@add_item']);
		Route::get('/edit_item/{itemid}', ['as' => 'edit_item', 'uses' => 'ItemController@edit_item']);

		Route::get('/inventory/{itemid}', ['as' => 'inventory', 'uses' => 'ItemController@inventory']);

		Route::post('/update_item', ['as' => 'update_item', 'uses' => 'ItemController@update_item']);
		
		Route::get('/delete_item', ['as' => 'delete_item', 'uses' => 'ItemController@delete_item']);
		Route::get('/items_json', ['as' => 'items_json', 'uses' => 'ItemController@items_json']);

		Route::get('/adjustment/{itemid}', ['as' => 'adjustment', 'uses' => 'ItemController@adjustment']);
	});

	#Spoilages
	Route::group(['prefix' => 'spoilages'], function(){
		Route::get('/', ['as' => 'spoilages', 'uses' => 'SpoilagesController@index']);
		Route::get('/add-spoilages', ['as' => 'add_spoilages_page', 'uses' => 'SpoilagesController@add_spoilages_page']);
		Route::post('/add-spoilage', ['as' => 'add_spoilage', 'uses' => 'SpoilagesController@add_spoilage']);
	});

	#purchase
	Route::group(['prefix' => 'purchases'], function(){
		Route::get('/', ['as' => 'purchases', 'uses' => 'PurchasesController@index']);	
		Route::get('/add-purchase', ['as' => 'add_purchase_page', 'uses' => 'PurchasesController@add_purchase_page']);	
		Route::post('/add-item-purchased', ['as' => 'add_item_purchased', 'uses' => 'PurchasesController@add_item_purchased']);	
		Route::post('/add-purchased-order', ['as' => 'add_purchased_order', 'uses' => 'PurchasesController@add_purchased_order']);

		Route::get('/view-purchase-details/{purchaseid}', ['as' => 'view_purchase_details', 'uses' => 'PurchasesController@view_purchase_details']);	

		Route::post('/submit-purchase', ['as' => 'add_purchase', 'uses' => 'PurchasesController@add_purchase']);	
		
	});

	#Category
	Route::group(['prefix' => 'category'], function(){
		Route::get('/', ['as' => 'category', 'uses' => 'CategoryController@index']);
		Route::get('/add_category_page', ['as' => 'add_category_page', 'uses' => 'CategoryController@add_category_page']);
		Route::get('/edit-category/{categoryid}', ['as' => 'edit_category', 'uses' => 'CategoryController@edit_category']);

		Route::post('/add_category', ['as' => 'add_category', 'uses' => 'CategoryController@add_category']);
		Route::get('/delete_category', ['as' => 'delete_category', 'uses' => 'CategoryController@delete_category']);
		Route::post('/update_category', ['as' => 'update_category', 'uses' => 'CategoryController@update_category']);
	});

	#Menu
	Route::group(['prefix' => 'menu'], function(){
		Route::get('/', ['as' => 'menu', 'uses' => 'MenuController@index']);		
		Route::get('/add-menu-page', ['as' => 'add_menu_page', 'uses' => 'MenuController@add_menu_page']);
		Route::post('/add_menu', ['as' => 'add_menu', 'uses' => 'MenuController@add_menu']);
		Route::get('/edit_menu/{menuid}', ['as' => 'edit_menu', 'uses' => 'MenuController@edit_menu']);
		Route::post('/update_menu/', ['as' => 'update_menu', 'uses' => 'MenuController@update_menu']);
		Route::get('/delete_menu/', ['as' => 'delete_menu', 'uses' => 'MenuController@delete_menu']);
		Route::get('/data-json', ['as' => 'menuDataJson', 'uses' => 'MenuController@menuDataJson']);

	#Recipes
		Route::get('/manage_recipes/{menuid}/', ['as' => 'manage_recipes', 'uses' => 'MenuController@manage_recipes']);
		Route::post('/add_recipe', ['as' => 'add_recipe', 'uses' => 'MenuController@add_recipe']);
		Route::get('/delete_recipe/{recipeid}/{menuid}', ['as' => 'delete_recipe', 'uses' => 'MenuController@delete_recipe']);
		# Menu json
	#Prices
		Route::get('/manage-prices/{menuid}/', ['as' => 'manage_prices', 'uses' => 'MenuController@manage_prices']);
		Route::post('/add-price', ['as' => 'add_price', 'uses' => 'MenuController@add_price']);

	});

	

	#Users
	Route::group(['prefix' => 'users', 'middleware' => 'auth'], function(){
		Route::get('/', ['as' => 'users', 'uses' => 'HomeController@users_list']);	

app/Purchases.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchases extends Model
{
    public $table = 'purchases';
    public $fillable = ['receipt', 'purchase_date'];
    public $timestamps = false;

    protected $dates = ['purchase_date'];

    public function PurchasedItems() {
    	return $this->hasMany('App\PurchasedItems', 'purchase_id');
    }

     public function getOfficialReceiptFormatAttribute()
    {
        return str_pad($this->receipt, 10, '0', STR_PAD_LEFT);
    }

}

resources/views/sales/or.blade.php
@extends('layouts.empty')

@section('content')
@parent
<style type="text/css">
body{
	font-size: 12px!important
}
.mdl-grid{
	margin: 0;
	padding: 0;
}
.mdl-grid .mdl-cell{
	padding-top: 0;
	padding-bottom: 0;
	margin-top: 0;
	margin-bottom: 0;
}
table th,
table td,
table tr{
	padding: 0!important;
	margin: 0!important;
	height: 0px!important;
}
table td{
	border: none!important;
}
table th{
	border-top: 1px solid rgba(0, 0, 0, 0.12);
	border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
</style>
	
	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--12-col text-center">{{ $company->name }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">{{ $company->address }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">Tel. No.: {{ $company->telephone_number }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">TIN: {{ $company->tin }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">S/N: {{ $terminal->hd_serial or "serial" }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">Owner: {{ $company->owner }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">Permit No.: {{ $company->permit_number }}</div>
		<div class="mdl-cell mdl-cell--12-col text-center">MIN: {{ $terminal->machine_id or "test" }}</div>
	</div>
	<br />
	<table class="mdl-data-table mdl-js-data-table" width="100%">
		<thead>
			<tr>
				<td class="text-left" colspan="1">O.R. No.</td>
				<td class="text-left" colspan="3">{{ $transaction->official_receipt_format }}</td>
			</tr>
			<tr>
				<td class="text-left" colspan="1">Table #</td>
				<td class="text-left" colspan="3">{{ $transaction->tables->name }}</td>
			</tr>
			<tr>
				<td class="text-left" colspan="1">Customer</td>
				<td class="text-left" colspan="3">{{ $transaction->customer_name }}</td>
			</tr>
			<tr>
				<td class="text-left" colspan="1">Staff</td>
				<td class="text-left" colspan="3">{{ $transaction->user->name }}</td>
			</tr>
			<tr>
				<td class="text-left" colspan="1">Date</td>
				<td class="text-left" colspan="3">{{ Carbon\Carbon::parse($transaction->transaction_datetime)->toDayDateTimeString() }}</td>
			</tr>
		    <tr>
		    	<th width="35%" class="mdl-data-table__cell--non-numeric">Description</th>
		    	<th width="25%" class="text-right">Price</th>
		    	<th width="15%" class="text-center">Qty</th>
		    	<th width="25%" class="text-right">Total</th>
		    </tr>
		</thead>
		<tbody>
			<!-- Start Loop -->
			@foreach($menus as $menu)
			<?php
			$total  += $menu->total_price;
			$vat  	+= $menu->vat_amount;
			#echo $menu->vat_amount;
			?>
			<tr>
				<td colspan="4" class="text-left">{{ $menu->pricing->menu->menu }} - {{ $menu->pricing->sizes->size }}</td>
			</tr>
			<tr>
				<td></td>
				<td class="text-right">{{ number_format($menu->price, 2) }}</td>
				<td class="text-center">{{ $menu->quantity }}</td>
				<td class="text-right">{{ number_format($menu->total_price, 2) }}</td>
			</tr>
			@endforeach
			<?php
			$discount = $total * $discount;
			$total -= $discount;
			?>
			<!-- End Loop -->
			<tr>
				<td colspan="4">&nbsp;</td>
			</tr>
			<tr class="afterItemList">
				<td class="text-right" colspan="2">Discount</td>
				<td class="text-right" colspan="2">{{ number_format($discount, 2) }}</td>
			</tr>
			<tr>
				<td class="text-right" colspan="2">Total</td>
				<td class="text-right" colspan="2">{{ number_format($total, 2) }}</td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
			<tr>
				<td class="text-right" colspan="2">Tendered</td>
				<td class="text-right" colspan="2">{{ number_format($tendered, 2) }}</td>
			</tr>
			<tr>
				<td class="text-right" colspan="2">Change</td>
				<td class="text-right" colspan="2">{{ number_format( ( $tendered - $total ), 2) }}</td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
			<tr>
				<td class="text-right" colspan="2">VATable</td>
				<td class="text-right" colspan="2">{{ number_format($vat, 2) }}</td>
			</tr>
			<tr>
				<td class="text-right" colspan="2">VAT</td>
				<td class="text-right" colspan="2">{{ number_format( ($total - $vat), 2) }}</td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
		</tbody>
	</table>
	<br />
	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--12-col text-center">THANK YOU, COME AGAIN!</div>
		<div class="mdl-cell mdl-cell--12-col text-center">THIS SERVE AS AN OFFICIAL RECEIPT</div>
	</div>
	<script type="text/javascript">
	$(document).ready(function(){
		setTimeout(function(){ window.print(); 	}, 1000);
		setTimeout(function(){ close(); 		}, 2000);
	});
	</script>
@endsection

resources/views/sales/verify.blade.php
@extends('layouts.empty')

@section('content')
@parent
<style type="text/css">
body{
	font-size: 12px!important
}
.mdl-grid{
	margin: 0;
	padding: 0;
}
.mdl-grid .mdl-cell{
	padding-top: 0;
	padding-bottom: 0;
	margin-top: 0;
	margin-bottom: 0;
}
table th,
table td,
table tr{
	padding: 0!important;
	margin: 0!important;
	height: 0px!important;
}
table td{
	border: none!important;
}
table th{
	border-top: 1px solid rgba(0, 0, 0, 0.12);
	border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
</style>
	<br />
	<table class="mdl-data-table mdl-js-data-table" width="100%">
		<thead>
			<tr>
				<th class="text-left">Table No : <strong>{{ $cash_register->table_reverse->name }} </strong></th>
				<th class="text-right">Customer Name :  <strong>{{ $cash_register->customer_name }} </strong></th>
			</tr>
			<tr>
				<th class="text-left">&nbsp;</th>
				<th class="text-right">&nbsp;</th>
			</tr>
			<tr>
				<th class="text-left">Menu </th>
				<th class="text-right">Selling Price </th>
			</tr>
		</thead>
		<tbody>
			<?php 
				$total = 0;
			?>
			@foreach($cash_register_menu as $menu)
			<?php 

				$total  += $menu->pricing->price;
			?>
			<tr>
				<td class="text-left">{{$menu->pricing->menu->menu}}</td>
				<td class="text-right">{{$menu->pricing->price}}</td>

			</tr>
			@endforeach
			<tr>
				<td>&nbsp;	</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="text-left"><strong>Total : </strong></td>
				<td class="text-right"><strong>{{ number_format($total,2) }}</strong></td>
			</tr>
		</tbody>
	</table>
	<br />
	
	<script type="text/javascript">
	$(document).ready(function(){
		setTimeout(function(){ window.print(); 	}, 1000);
		setTimeout(function(){ close(); 		}, 2000);
	});
	</script>
@endsection